### PR TITLE
belay select

### PR DESCRIPTION
**Pull request by BrianPugh**
# Features
* Naively remove "bad" return values from `list_devices`.
* Make the first argument `device` of `Pyboard` optional. If not provided, will attempt to read the `BELAY_DEVICE` environment variable. If not available, it will attempt to connect to a plausible device if there's only 1 plausible device available.
* Add `belay select`, an interactive command for blinking device LEDs and exporting usb specifiers.

# Breaking
* Removed `belay identify`; replaced with `belay select`.

# TODO prior to merging:
* Have @raveslave provide feedback on usage.
* Increase documentation.

# Screenshots

Screenshot 2023-04-16 at 8 34 07 AM

Screenshot 2023-04-16 at 9 06 48 AM

### CODE REVIEW

**Comment by raveslave** [comment]
reviewed the commits, looks clean and well thought out. will use it a bit with real hardware next week to see if anything obvious comes up. 

this is really what I've missed with both pyboard, mpremote or any python-lib interacting with cdc-ddevices for that matter.

**Comment by BrianPugh** [comment]
sounds good! I'll leave this PR up in the meantime. I'll also try to flesh out the docs a bit more.

**Comment by BrianPugh** [comment]
@raveslave have you had a chance to play with this?

**Comment by BrianPugh** [comment]
Another TODO: we need to figure out a way of making the CLI's fun to use with this new addition. Currently all commands are `belay command PORT`, but PORT can now be substituted out with the environment variable `$BELAY_DEVICE`. Maybe it's best to just have it remain as the user explicitly specifying `belay command $BELAY_DEVICE`.

**Comment by BrianPugh** [comment]
for now, I'm just going to leave it explicitly up to the user to call `belay command $BELAY_DEVICE`, we can always improve upon this in the future.

**Comment by raveslave** [comment]
> @raveslave have you had a chance to play with this?

took a while but now yes! I think it came out really neat, very easy to use

**Comment by BrianPugh** [comment]
Thanks! I really wish I could have it set env vars for us, but it seems impossible. If you ever run into something that could help in this area, please let me know!

**Comment by raveslave** [comment]
same here, will ask around!

**Pull request merged**
